service: bamboo-server
useDotenv: true

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-2
  stage: api

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: "ApiGatewayRestApi"

functions:
  # hello:
  #   handler: handler.hello
  #   events:
  #     - http:
  #         path: /
  #         method: get
  #   cors:
  #     origin: "*"
  post:
    handler: src/sls.handler
    events:
      - http:
          path: post/get-list
          method: get
          cors: true
      - http:
          path: post/create
          method: post
          cors: true
      - http:
          path: post/patch/{id}
          method: patch
          cors: true
      - http:
          path: post/delete/{arg}
          method: delete
          cors: true
      # - http:
      #     path: /
      #     method: get

  auth:
    handler: src/handler.authAdmin
    events:
      - http:
          path: auth
          method: post
          cors: true
  verify:
    handler: src/handler.getVerifyQuestion
    events:
      - http:
          path: verify
          method: get
          cors: true
plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline
custom:
  dotenv:
    required:
      env:
        - PORT
        - MONGO_URL
        - DISCORD_WEBHOOK
        - DISCORD_TEST_WEBHOOK
        - DISCORD_MANAGEMENT_WEBHOOK
        - ADMIN_PASSWORD
        - JWT_SECRET
